"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Boxes, CheckCircle2, ExternalLink, FileText, Layers3, PlugZap } from "lucide-react";
import { clientProjects } from "@/data/client-portal/client-portal-mock-data";
import type { ClientProjectBlock } from "@/types/client-portal";
import { ClientPortalBadge } from "@/components/client-portal/ui/ClientPortalBadge";
import { ClientPortalCard } from "@/components/client-portal/ui/ClientPortalCard";
import { ClientPortalModal } from "@/components/client-portal/ui/ClientPortalModal";
import { ClientPortalPageHeader } from "@/components/client-portal/ui/ClientPortalPageHeader";
import { projectStatusLabel, statusVariant } from "@/components/client-portal/ui/client-portal-status";

function BlockList({ title, icon: Icon, items, onOpen }: { title: string; icon: typeof Layers3; items: ClientProjectBlock[]; onOpen: (item: ClientProjectBlock) => void }) {
  return <ClientPortalCard className="p-6"><div className="mb-5 flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100"><Icon className="h-4 w-4" /></span><h2 className="font-bold text-slate-900">{title}</h2></div><div className="space-y-3">{items.map((item) => <button key={item.id} type="button" onClick={() => onOpen(item)} className="flex w-full items-center justify-between rounded-xl border border-slate-100 p-4 text-left hover:bg-slate-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-black"><span><span className="block text-sm font-semibold text-slate-900">{item.title}</span><span className="mt-1 block text-xs text-slate-500">{item.description}</span></span><ClientPortalBadge variant={statusVariant(item.status)}>{projectStatusLabel[item.status]}</ClientPortalBadge></button>)}</div></ClientPortalCard>;
}

export function ClientProjectPage() {
  const [projectId, setProjectId] = useState(clientProjects[0].id);
  const [detail, setDetail] = useState<ClientProjectBlock | null>(null);
  const project = clientProjects.find((item) => item.id === projectId) ?? clientProjects[0];
  return <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><ClientPortalPageHeader eyebrow="Escopo contratado" title="Meu projeto" description="Consulte o briefing, entregaveis e tudo que esta previsto no projeto." actions={<label className="text-xs font-semibold text-slate-500">Projeto atual<select value={projectId} onChange={(event) => setProjectId(Number(event.target.value))} className="ml-3 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:ring-2 focus:ring-black">{clientProjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>} />
    <ClientPortalCard className="mb-6 p-6"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><ClientPortalBadge variant={statusVariant(project.status)}>{projectStatusLabel[project.status]}</ClientPortalBadge><h2 className="mt-4 text-xl font-bold text-slate-900">{project.name}</h2><p className="mt-1 text-sm text-slate-500">{project.type} · Plano {project.plan}</p></div><div className="md:text-right"><p className="text-xs uppercase tracking-wider text-slate-400">Prazo estimado</p><p className="mt-2 font-semibold text-slate-900">{project.estimatedDeadline}</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4 md:col-span-2"><p className="text-[10px] uppercase tracking-wider text-slate-400">Briefing resumido</p><p className="mt-2 text-sm leading-6 text-slate-600">{project.briefing}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Publico-alvo</p><p className="mt-2 text-sm leading-6 text-slate-600">{project.audience}</p></div></div><div className="mt-4 rounded-xl border border-slate-100 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Objetivo</p><p className="mt-2 text-sm leading-6 text-slate-600">{project.objective}</p></div></ClientPortalCard>
    <div className="mb-6 grid gap-6 xl:grid-cols-3"><BlockList title="Funcionalidades" icon={Boxes} items={project.features} onOpen={setDetail} /><BlockList title="Integracoes" icon={PlugZap} items={project.integrations} onOpen={setDetail} /><BlockList title="Entregaveis" icon={FileText} items={project.deliverables} onOpen={setDetail} /></div>
    <div className="grid gap-6 lg:grid-cols-2"><ClientPortalCard className="p-6"><h2 className="font-bold text-slate-900">Paginas incluidas</h2><div className="mt-4 flex flex-wrap gap-2">{project.pages.map((page) => <span key={page} className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-medium text-slate-700">{page}</span>)}</div><h3 className="mt-6 text-sm font-bold text-slate-900">Tecnologias previstas</h3><div className="mt-3 flex flex-wrap gap-2">{project.technologies.map((technology) => <ClientPortalBadge key={technology}>{technology}</ClientPortalBadge>)}</div></ClientPortalCard><ClientPortalCard className="p-6"><h2 className="font-bold text-slate-900">Links e observacoes</h2><div className="mt-4 space-y-3">{project.usefulLinks.map((link) => <a key={link.label} href={link.url} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-slate-100 p-4 text-sm font-semibold text-slate-800 hover:bg-slate-50">{link.label}<ExternalLink className="h-4 w-4" /></a>)}</div><ul className="mt-5 space-y-2 text-xs leading-5 text-slate-500">{project.notes.map((note) => <li key={note} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-slate-400" />{note}</li>)}</ul><Link href="/cliente/solicitacoes" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-black px-4 py-2.5 text-sm font-semibold text-white">Solicitar mudanca<ArrowUpRight className="h-4 w-4" /></Link></ClientPortalCard></div>
    {detail ? <ClientPortalModal title={detail.title} description={detail.description} onClose={() => setDetail(null)}><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span className="text-sm text-slate-500">Status deste bloco</span><ClientPortalBadge variant={statusVariant(detail.status)}>{projectStatusLabel[detail.status]}</ClientPortalBadge></div></ClientPortalModal> : null}
  </div>;
}
