import Link from "next/link";
import { ArrowRight, CalendarClock, CheckCircle2, CircleAlert, FolderOpen, LifeBuoy } from "lucide-react";
import { clientApprovals, clientPortalUser, clientProjects, clientRecentUpdates, clientTeam } from "@/data/client-portal/client-portal-mock-data";
import { clientPortalQuickLinks } from "@/data/client-portal/client-portal-navigation";
import { ClientPortalBadge } from "@/components/client-portal/ui/ClientPortalBadge";
import { ClientPortalCard } from "@/components/client-portal/ui/ClientPortalCard";
import { ClientPortalPageHeader } from "@/components/client-portal/ui/ClientPortalPageHeader";
import { projectStatusLabel, statusVariant } from "@/components/client-portal/ui/client-portal-status";
import { CrmAvatar } from "@/components/crm/ui/CrmAvatar";

export function ClientOverviewPage() {
  const project = clientProjects.find((item) => item.id === clientPortalUser.currentProjectId) ?? clientProjects[0];
  const manager = clientTeam.find((item) => item.id === project.managerId) ?? clientTeam[0];
  const pendingApprovals = clientApprovals.filter((item) => item.status === "pending").length;

  return <div className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8"><ClientPortalPageHeader eyebrow="Portal do Cliente Ateliux" title={`Ola, ${clientPortalUser.name.split(" ")[0]}`} description={`Seu projeto esta em fase de ${project.currentStage}. A proxima etapa e ${project.nextStage.toLowerCase()}.`} actions={<Link href="/cliente/projeto" className="inline-flex items-center gap-2 rounded-xl bg-black px-4 py-2.5 text-sm font-semibold text-white hover:bg-zinc-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-black focus-visible:ring-offset-2">Ver meu projeto<ArrowRight className="h-4 w-4" /></Link>} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,0.85fr)]"><div className="space-y-6"><ClientPortalCard className="p-6"><div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div><ClientPortalBadge variant={statusVariant(project.status)}>{projectStatusLabel[project.status]}</ClientPortalBadge><h2 className="mt-4 text-xl font-bold text-slate-900">{project.name}</h2><p className="mt-1 text-sm text-slate-500">{project.type} · Plano {project.plan}</p></div><div className="text-left sm:text-right"><p className="text-3xl font-bold text-slate-900">{project.progress}%</p><p className="mt-1 text-xs text-slate-400">Progresso geral</p></div></div><div className="mt-6 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-black" style={{ width: `${project.progress}%` }} /></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Etapa atual</p><p className="mt-2 text-sm font-semibold text-slate-900">{project.currentStage}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Proxima etapa</p><p className="mt-2 text-sm font-semibold text-slate-900">{project.nextStage}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-400">Prazo estimado</p><p className="mt-2 text-sm font-semibold text-slate-900">{project.estimatedDeadline}</p></div></div></ClientPortalCard>
      <div className="grid gap-6 md:grid-cols-2"><ClientPortalCard className="p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-bold text-slate-900">Pendencias para voce</h2><CircleAlert className="h-5 w-5 text-amber-500" /></div><Link href="/cliente/aprovacoes" className="flex items-start gap-3 rounded-xl border border-amber-100 bg-amber-50/60 p-4 hover:bg-amber-50"><CheckCircle2 className="mt-0.5 h-5 w-5 text-amber-600" /><span><span className="block text-sm font-semibold text-slate-900">{pendingApprovals} aprovacoes pendentes</span><span className="mt-1 block text-xs leading-5 text-slate-500">Revise a home para manter o cronograma.</span></span></Link><Link href="/cliente/arquivos" className="mt-3 flex items-start gap-3 rounded-xl border border-slate-100 p-4 hover:bg-slate-50"><FolderOpen className="mt-0.5 h-5 w-5 text-slate-500" /><span><span className="block text-sm font-semibold text-slate-900">Enviar textos finais</span><span className="mt-1 block text-xs text-slate-500">Prazo sugerido: esta semana.</span></span></Link></ClientPortalCard>
        <ClientPortalCard className="p-6"><h2 className="mb-5 font-bold text-slate-900">Responsavel principal</h2><div className="flex items-center gap-4"><CrmAvatar src={manager.avatar} alt={`Foto de ${manager.name}`} size="lg" /><div><p className="font-semibold text-slate-900">{manager.name}</p><p className="text-sm text-slate-500">{manager.role}</p><ClientPortalBadge variant="success">Disponivel</ClientPortalBadge></div></div><div className="mt-5 flex gap-3"><Link href="/cliente/equipe" className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Ver equipe</Link><Link href="/cliente/suporte" className="rounded-xl bg-black px-4 py-2 text-xs font-semibold text-white">Falar com a Ateliux</Link></div></ClientPortalCard></div>
      <ClientPortalCard className="p-6"><div className="mb-5 flex items-center justify-between"><h2 className="font-bold text-slate-900">Ultimas atualizacoes</h2><Link href="/cliente/historico" className="text-xs font-semibold text-slate-600 hover:text-black">Ver historico</Link></div><div className="space-y-4">{clientRecentUpdates.map((item) => <div key={item.id} className="flex gap-4 border-b border-slate-100 pb-4 last:border-0 last:pb-0"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-black" /><div className="flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-900">{item.title}</p><span className="text-[11px] text-slate-400">{item.date}, {item.time}</span></div><p className="mt-1 text-xs leading-5 text-slate-500">{item.description}</p></div></div>)}</div></ClientPortalCard></div>
      <div className="space-y-6"><ClientPortalCard className="p-5"><h2 className="mb-4 font-bold text-slate-900">Acesso rapido</h2><div className="grid grid-cols-2 gap-3">{clientPortalQuickLinks.map((item) => <Link key={item.href} href={item.href} className="rounded-xl border border-slate-100 p-4 hover:border-slate-300 hover:bg-slate-50"><item.icon className="h-5 w-5 text-black" /><span className="mt-3 block text-xs font-semibold text-slate-800">{item.label}</span></Link>)}</div></ClientPortalCard><ClientPortalCard className="p-5"><div className="flex items-center gap-3"><CalendarClock className="h-5 w-5" /><h2 className="font-bold text-slate-900">Proximo marco</h2></div><p className="mt-4 text-sm font-semibold text-slate-900">Entrega da primeira versao</p><p className="mt-1 text-xs leading-5 text-slate-500">Telas principais disponiveis para sua revisao.</p><Link href="/cliente/cronograma" className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-black">Abrir cronograma<ArrowRight className="h-3.5 w-3.5" /></Link></ClientPortalCard><ClientPortalCard className="bg-black p-5 text-white"><LifeBuoy className="h-6 w-6" /><h2 className="mt-4 font-bold">Precisa de ajuda?</h2><p className="mt-2 text-xs leading-5 text-zinc-400">Nossa equipe acompanha seu projeto de perto.</p><Link href="/cliente/suporte" className="mt-4 inline-flex rounded-lg bg-white px-4 py-2 text-xs font-semibold text-black">Abrir suporte</Link></ClientPortalCard></div></div>
  </div>;
}
