CREATE TYPE "FileRiskLevel" AS ENUM ('SAFE_PREVIEW', 'DOWNLOAD_ONLY', 'HIGH_RISK_DOWNLOAD_ONLY');

CREATE TYPE "FileDownloadMode" AS ENUM ('INLINE_ALLOWED', 'ATTACHMENT_ONLY');

ALTER TABLE "FileAsset"
  ADD COLUMN "riskLevel" "FileRiskLevel" NOT NULL DEFAULT 'DOWNLOAD_ONLY',
  ADD COLUMN "downloadMode" "FileDownloadMode" NOT NULL DEFAULT 'ATTACHMENT_ONLY';
